### ISSUE TITLE
ModuleNotFoundError: No module named 'gpt3' in glados-test.py

### ISSUE THREAD

**Issue by DamascusGit** [mikepfrank/GLaDOS#1]
**Steps to Reproduce**

1. Clone the repository at [https://github.com/mikepfrank/GLaDOS.git](https://github.com/mikepfrank/GLaDOS.git).
2. Install the required dependencies using pip3 install openai, backoff
3. Load API access key as env variable
4. Run the test file with the command python3 src/test/glados-test.py.

**Expected Behavior**
The test file should run successfully and all modules should be imported without any errors.

**Actual Behavior**
The test file fails to run, throwing a ModuleNotFoundError exception for the gpt3 module.

**Error Message**
```
Traceback (most recent call last):
  File "/Users/DamascusGit/David/GLaDOS/src/test/glados-test.py", line 14, in <module>
    from gpt3.api import *
ModuleNotFoundError: No module named 'gpt3'
```

Would love to get this running, it looks like a one of a kind project. Please let me know what I'm doing wrong here!

It's probably a PATH thing or something, tried to run this on OSX and Windows systems on VSCode.

**Comment by mikepfrank** [comment]
Oh you just need to 'cd src' before running the test file

**Comment by mikepfrank** [comment]
no wait... don't do that; instead just do 

mv src/test/glados-test.py src
python3 src/glados-test.py

**Comment by mikepfrank** [comment]
The test script had several issues... just pushed a commit that fixes it:
8d41b95a4f0e5013d2b8580a59a40892a7834174
